### ISSUE TITLE
import-entries error on OS X El Capitan

### ISSUE THREAD

**Issue by oddmouse** [contentful/contentful-importer.rb#25]
I'm using this after successfully exporting from the `wordpress-exporter`. The `import-content-model` command works perfectly and the `import` command works up until the entry part and then gives the same output:
```sh
$ contentful-importer --configuration=settings.yml import-entries
/usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.1/lib/contentful/importer/data_organizer.rb:28:in `/': divided by 0 (ZeroDivisionError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.1/lib/contentful/importer/data_organizer.rb:28:in `split_entries'
	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.1/lib/contentful/importer/data_organizer.rb:19:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.1/lib/contentful/importer/parallel_importer.rb:31:in `import_data'
	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.1/lib/contentful/importer/import_entries.rb:14:in `import'
	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.1/lib/contentful/importer/import_entries.rb:19:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/contentful-importer-0.2.1/bin/contentful-importer:12:in `<top (required)>'
	from /usr/local/bin/contentful-importer:22:in `load'
	from /usr/local/bin/contentful-importer:22:in `<main>'
```

Here is my `settings.yml`:
```yml
#PATH to all data
data_dir: exported/news

########## IMPORT DATA TO CONTENTFUL ##########

## EXPORTED XML FILE FROM WORDPRESS
wordpress_xml_path: wordpress_settings/wp-news-2016-02-03.xml

## CONVERT CONTENTFUL MODEL TO CONTENTFUL IMPORT STRUCTURE
content_model_json: wordpress_settings/contentful_model.json
converted_model_dir: wordpress_settings/contentful_structure.json

contentful_structure_dir: wordpress_settings/default_contentful_structure.json

# Contentful credentials
access_token: XXX
organization_id: XXX
space_id: XXX
default_locale: en-US
```
